write_mode = "overwrite"

format_strings = false

reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true

array_layout = "Block"
array_width = 120

tab_spaces = 4
hard_tabs = true

enum_trailing_comma = true
match_block_trailing_comma = true
struct_trailing_comma = "Always"
wrap_comments = true
trailing_comma = "Vertical"

report_todo = "Always"
report_fixme = "Always"

max_width = 120
ideal_width = 120
fn_call_width = 100